spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  spring:
    redis:
      host: localhost
      port: 6379
server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG
jwt:
  secret: Nzg5YTJmMzktNDMxNi00NzlhLThhNmYtZDE1OTk2YjYwYzA5  # base64 encoded
  expiration: 86400000 # 1天 (毫秒)
